# Generated by Django 5.2.4 on 2025-12-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_id_alter_profile_user_alter_user_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follow_visibility',
            field=models.CharField(choices=[('public', '전체 공개'), ('followers', '내 팔로워에게만 공개'), ('private', '비공개')], default='public', max_length=20, verbose_name='팔로우 목록 공개 범위'),
        ),
    ]
