# Generated by Django 5.2.4 on 2025-12-19 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_follow_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='share_trip',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='대표 이미지'),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/multiple/', verbose_name='사진')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.post', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '게시글 사진',
                'verbose_name_plural': '게시글 사진',
            },
        ),
    ]
