
# Generated by Django 5.2.4 on 2025-12-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_postimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keywords',
            field=models.JSONField(blank=True, default=list, verbose_name='선호 키워드'),
        ),
    ]
