# Generated by Django 5.2.4 on 2025-12-20 03:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BakeryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': 'Bakery Comment',
                'verbose_name_plural': 'Bakery Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BakeryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': 'Bakery Like',
                'verbose_name_plural': 'Bakery Likes',
            },
        ),
        migrations.RemoveField(
            model_name='bakery',
            name='operating_hours',
        ),
        migrations.AddField(
            model_name='bakery',
            name='business_hours_raw',
            field=models.TextField(blank=True, verbose_name='영업시간 원본'),
        ),
        migrations.AddField(
            model_name='bakery',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='bakery',
            name='comment_count',
            field=models.PositiveIntegerField(default=0, verbose_name='댓글 수'),
        ),
        migrations.AddField(
            model_name='bakery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bakery',
            name='district',
            field=models.CharField(blank=True, max_length=50, verbose_name='구'),
        ),
        migrations.AddField(
            model_name='bakery',
            name='friday',
            field=models.CharField(blank=True, max_length=100, verbose_name='금요일'),
        ),
        migrations.AddField(
            model_name='bakery',
            name='jibun_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='지번 주소'),
        ),
        migrations.AddField(
            model_name='bakery',
            name='kakao_rate',
            field=models.CharField(blank=True, max_length=10, verbose_name='카카오 평점'),
        ),
        migrations.AddField(
            model_name='bakery',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='bakery',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='좋아요 수'),
        ),
        migrations.AddField(
            model_name='bakery',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='경도'),
        ),
        migrations.AddField(
            model_name='bakery',
            name='monday',
            field=models.CharField(blank=True, max_length=100, verbose_name='월요일'),
        ),
        migrations.AddField(
            model_name='bakery',
            name='naver_rate',
            field=models.CharField(blank=True, max_length=10, verbose_name='네이버 평점'),
        ),
        migrations.AddField(
            model_name='bakery',
            name='saturday',
            field=models.CharField(blank=True, max_length=100, verbose_name='토요일'),
        ),
        migrations.AddField(
            model_name='bakery',
            name='slug_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='영문 슬러그'),
        ),
        migrations.AddField(
            model_name='bakery',
            name='sunday',
            field=models.CharField(blank=True, max_length=100, verbose_name='일요일'),
        ),
        migrations.AddField(
            model_name='bakery',
            name='thursday',
            field=models.CharField(blank=True, max_length=100, verbose_name='목요일'),
        ),
        migrations.AddField(
            model_name='bakery',
            name='tuesday',
            field=models.CharField(blank=True, max_length=100, verbose_name='화요일'),
        ),
        migrations.AddField(
            model_name='bakery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AddField(
            model_name='bakery',
            name='wednesday',
            field=models.CharField(blank=True, max_length=100, verbose_name='수요일'),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='keywords',
            field=models.TextField(blank=True, verbose_name='키워드'),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='name',
            field=models.CharField(max_length=255, verbose_name='빵집 이름'),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='road_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='도로명 주소'),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='url',
            field=models.URLField(blank=True, verbose_name='지도 URL'),
        ),
        migrations.AddIndex(
            model_name='bakery',
            index=models.Index(fields=['district'], name='chatbot_bak_distric_e87638_idx'),
        ),
        migrations.AddIndex(
            model_name='bakery',
            index=models.Index(fields=['name'], name='chatbot_bak_name_71c17c_idx'),
        ),
        migrations.AddField(
            model_name='bakerycomment',
            name='bakery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='chatbot.bakery', verbose_name='빵집'),
        ),
        migrations.AddField(
            model_name='bakerycomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bakery_comments', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='bakerylike',
            name='bakery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='chatbot.bakery', verbose_name='빵집'),
        ),
        migrations.AddField(
            model_name='bakerylike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bakery_likes', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddIndex(
            model_name='bakerycomment',
            index=models.Index(fields=['bakery', '-created_at'], name='chatbot_bak_bakery__b89816_idx'),
        ),
        migrations.AddIndex(
            model_name='bakerylike',
            index=models.Index(fields=['bakery', '-created_at'], name='chatbot_bak_bakery__6ce915_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bakerylike',
            unique_together={('user', 'bakery')},
        ),
    ]
