# Generated by Django 5.2.4 on 2025-12-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_bakerycomment_bakerylike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakery',
            name='kakao_rate',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='카카오 평점'),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='naver_rate',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='네이버 평점'),
        ),
    ]
