# Generated by Django 5.2.4 on 2025-12-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_bakery_kakao_rate_alter_bakery_naver_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakery',
            name='kakao_rate',
        ),
        migrations.RemoveField(
            model_name='bakery',
            name='naver_rate',
        ),
        migrations.AddField(
            model_name='bakery',
            name='rate',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Tripsnap 평점'),
        ),
    ]
