# Generated by Django 5.2.4 on 2025-12-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_remove_bakery_kakao_rate_remove_bakery_naver_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakery',
            name='rate',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Tripsnap 평점'),
        ),
    ]
