# Generated by Django 5.2.4 on 2025-12-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_bakery_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakery',
            name='rate',
            field=models.FloatField(blank=True, default='', max_length=10, null=True, verbose_name='Tripsnap 평점'),
        ),
    ]
